# Build and Deploy to dev env.
# Trigger with tag dev
# Connected with repo environment 'dev'
name: Deploy application with tag

on:
  push:
    tags:
      - test
      - prod

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  BUILD_REF: ${{ github.base_ref }}
  APP_CONFIG_DEV: ${{ vars.APP_CONFIG_DEV }}
  APP_CONFIG_TEST: ${{ vars.APP_CONFIG_TEST }}
  APP_CONFIG_PROD: ${{ vars.APP_CONFIG_PROD }}
jobs:
  api:
    name: OpenShift Deploy
    runs-on: ubuntu-latest
    concurrency: ci-deploy-api-dev
    timeout-minutes: 20
    steps:
      - name: Set env
        run: echo "ENV_PREFIX=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy changes
        working-directory: "./tools"
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          make print-status
          make api-create-certificate
          make init-api
          make promote-api
          make deploy-api
